name: Build Backend
description: Builds backend application

runs:
  using: composite
  steps:
    - name: Build backend
      run: |
        echo "Building @apps/backend..."
        pnpm --filter @apps/backend build
      shell: bash
